pr: ["master"]

resources:
  containers:
    - container: rust
      image: rust:latest

jobs:
  - job: tests
    pool:
      vmImage: 'ubuntu-16.04'
    displayName: "test --all"
    steps:
      - template: ci/install-rust.yml
        parameters:
          rust_version: nightly
      - bash: |
          export RUST_BACKTRACE=1
          cargo test --all || exit
        displayName: "Run cargo test"
  - job: check_benches
    pool:
      vmImage: 'ubuntu-16.04'
    displayName: "check --benches"
    steps:
      - template: ci/install-rust.yml
        parameters:
          rust_version: nightly
      - bash: |
          cargo check --benches || exit
        displayName: "Run cargo check"
  - template: ci/rustfmt.yml
    parameters:
      displayName: "cargo fmt --check"
